apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-app
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: "stackexpresskush/web-test:latest"
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
